apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit
  namespace: ${namespace}
spec:
  limits:
  - default:
      memory: "1024Mi"
      cpu: "1000m"
      ephemeral-storage: "4Gi" 
    defaultRequest:
      memory: "512Mi"
      cpu: "500m"
      ephemeral-storage: "2Gi"
    type: Container