---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${namespace}-tenant
  namespace: ${namespace}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${namespace}-user
  namespace: ${namespace}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
- apiGroups: ["extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
- apiGroups: [""]
  resources: 
  - configmaps
  - endpoints
  - limitranges
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - pods
  - pods/attach
  - pods/binding
  - pods/eviction
  - pods/exec
  - pods/log
  - pods/portforward
  - pods/proxy
  - pods/status
  - podtemplates
  - replicationcontrollers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  - secrets
  - serviceaccounts
  - serviceaccounts/token
  - services
  - services/status
  verbs: ["*"]
- apiGroups: [""]
  resources: 
  - resourcequotas
  verbs: ["get", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${namespace}-user-view
  namespace: ${namespace}
subjects:
- kind: ServiceAccount
  name: ${namespace}-tenant
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${namespace}-user

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tenant-cluster-user
rules:
- apiGroups: ["storage.k8s.io"]
  resources: 
  - storageclasses
  verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${namespace}-user-cluster-view
subjects:
- kind: ServiceAccount
  name: ${namespace}-tenant
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-cluster-user