---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${namespace}-user
  namespace: ${namespace}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${namespace}-user-view
  namespace: ${namespace}
subjects:
- kind: ServiceAccount
  name: ${namespace}-user
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${namespace}-user-full-access