---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${namespace}-tenant
  namespace: ${namespace}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${namespace}-user
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ${namespace}-user-view
subjects:
- kind: ServiceAccount
  name: ${namespace}-tenant
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${namespace}-user