apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ${namespace}
spec:
  hard:
    #requests.cpu: "2"
    #requests.memory: 2Gi
    limits.cpu: "${cpu}"
    limits.memory: "${memory}Gi"
    limits.ephemeral-storage: "${ephemeral}Gi"
    requests.storage: "${storage}Gi"
    requests.nvidia.com/gpu: "${gpu}"